spring.datasource.url=jdbc:postgresql://localhost:5432/plantAPI
spring.datasource.username=secret
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none


# Enable SQL logging for Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Show SQL parameters (important for debugging actual queries)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework.web=DEBUG

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000